name: GoldenBlockEvent
version: '${project.version}'
main: me.vanilar.goldenblockevent.GoldenBlockEvent
api-version: '1.20'

commands:
  goldenblockevent:
    description: main plugin command
    aliases:
      - goldenblock
      - gbevent
      - gbe
